# version: '3.8'
services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  backend:
    container_name: foodgram-backend
    build: ../backend
    env_file: ../backend/.env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ../backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/app/media/
    depends_on:
      - backend

volumes:
  pg_data:
  static:
  media:
